CREATE TABLE alpena_county(
	Year INT NOT NULL, 
	Month INT NOT NULL,
	Day INT NOT NULL,
	Hour INT NOT NULL,
	Minute INT NOT NULL,
	DHI FLOAT NOT NULL,
	DNI FLOAT NOT NULL,
	GHI FLOAT NOT NULL,
	Clearsky_DHI FLOAT NOT NULL,
	Clearsky_DNI FLOAT NOT NULL,
	Clearsky_GHI FLOAT NOT NULL,
	Cloud_Type FLOAT NOT NULL,
	Dew_Point FLOAT NOT NULL,
	Solar_Zenith_Angle FLOAT NOT NULL,
	Fill_Flag FLOAT NOT NULL,
	Surface_Albedo FLOAT NOT NULL,
	Wind_Speed FLOAT NOT NULL,
	Precipitable_Water FLOAT NOT NULL,
	Wind_Direction FLOAT NOT NULL,
	Relative_Humidity FLOAT NOT NULL,
	Temperature FLOAT NOT NULL,
	Pressure FLOAT NOT NULL,
	Global_Horizontal_UV_Irradiance_280to400nm FLOAT NOT NULL,
	Global_Horizontal_UV_Irradiance_295to385nm FLOAT NOT NULL
);

CREATE TABLE calhoun_county_2018_battlecreek(
	Year INT NOT NULL, 
	Month INT NOT NULL,
	Day INT NOT NULL,
	Hour INT NOT NULL,
	Minute INT NOT NULL,
	DHI FLOAT NOT NULL,
	DNI FLOAT NOT NULL,
	GHI FLOAT NOT NULL,
	Clearsky_DHI FLOAT NOT NULL,
	Clearsky_DNI FLOAT NOT NULL,
	Clearsky_GHI FLOAT NOT NULL,
	Cloud_Type FLOAT NOT NULL,
	Dew_Point FLOAT NOT NULL,
	Solar_Zenith_Angle FLOAT NOT NULL,
	Fill_Flag FLOAT NOT NULL,
	Surface_Albedo FLOAT NOT NULL,
	Wind_Speed FLOAT NOT NULL,
	Precipitable_Water FLOAT NOT NULL,
	Wind_Direction FLOAT NOT NULL,
	Relative_Humidity FLOAT NOT NULL,
	Temperature FLOAT NOT NULL,
	Pressure FLOAT NOT NULL,
	Global_Horizontal_UV_Irradiance_280to400nm FLOAT NOT NULL,
	Global_Horizontal_UV_Irradiance_295to385nm FLOAT NOT NULL
);

CREATE TABLE genesee_county_2018_flint(
	Year INT NOT NULL, 
	Month INT NOT NULL,
	Day INT NOT NULL,
	Hour INT NOT NULL,
	Minute INT NOT NULL,
	DHI FLOAT NOT NULL,
	DNI FLOAT NOT NULL,
	GHI FLOAT NOT NULL,
	Clearsky_DHI FLOAT NOT NULL,
	Clearsky_DNI FLOAT NOT NULL,
	Clearsky_GHI FLOAT NOT NULL,
	Cloud_Type FLOAT NOT NULL,
	Dew_Point FLOAT NOT NULL,
	Solar_Zenith_Angle FLOAT NOT NULL,
	Fill_Flag FLOAT NOT NULL,
	Surface_Albedo FLOAT NOT NULL,
	Wind_Speed FLOAT NOT NULL,
	Precipitable_Water FLOAT NOT NULL,
	Wind_Direction FLOAT NOT NULL,
	Relative_Humidity FLOAT NOT NULL,
	Temperature FLOAT NOT NULL,
	Pressure FLOAT NOT NULL,
	Global_Horizontal_UV_Irradiance_280to400nm FLOAT NOT NULL,
	Global_Horizontal_UV_Irradiance_295to385nm FLOAT NOT NULL
);

CREATE TABLE gogebic_county_2018_ironwoodwestup(
	Year INT NOT NULL, 
	Month INT NOT NULL,
	Day INT NOT NULL,
	Hour INT NOT NULL,
	Minute INT NOT NULL,
	DHI FLOAT NOT NULL,
	DNI FLOAT NOT NULL,
	GHI FLOAT NOT NULL,
	Clearsky_DHI FLOAT NOT NULL,
	Clearsky_DNI FLOAT NOT NULL,
	Clearsky_GHI FLOAT NOT NULL,
	Cloud_Type FLOAT NOT NULL,
	Dew_Point FLOAT NOT NULL,
	Solar_Zenith_Angle FLOAT NOT NULL,
	Fill_Flag FLOAT NOT NULL,
	Surface_Albedo FLOAT NOT NULL,
	Wind_Speed FLOAT NOT NULL,
	Precipitable_Water FLOAT NOT NULL,
	Wind_Direction FLOAT NOT NULL,
	Relative_Humidity FLOAT NOT NULL,
	Temperature FLOAT NOT NULL,
	Pressure FLOAT NOT NULL,
	Global_Horizontal_UV_Irradiance_280to400nm FLOAT NOT NULL,
	Global_Horizontal_UV_Irradiance_295to385nm FLOAT NOT NULL
);

CREATE TABLE grand_traverse_2018(
	Year INT NOT NULL, 
	Month INT NOT NULL,
	Day INT NOT NULL,
	Hour INT NOT NULL,
	Minute INT NOT NULL,
	DHI FLOAT NOT NULL,
	DNI FLOAT NOT NULL,
	GHI FLOAT NOT NULL,
	Clearsky_DHI FLOAT NOT NULL,
	Clearsky_DNI FLOAT NOT NULL,
	Clearsky_GHI FLOAT NOT NULL,
	Cloud_Type FLOAT NOT NULL,
	Dew_Point FLOAT NOT NULL,
	Solar_Zenith_Angle FLOAT NOT NULL,
	Fill_Flag FLOAT NOT NULL,
	Surface_Albedo FLOAT NOT NULL,
	Wind_Speed FLOAT NOT NULL,
	Precipitable_Water FLOAT NOT NULL,
	Wind_Direction FLOAT NOT NULL,
	Relative_Humidity FLOAT NOT NULL,
	Temperature FLOAT NOT NULL,
	Pressure FLOAT NOT NULL,
	Global_Horizontal_UV_Irradiance_280to400nm FLOAT NOT NULL,
	Global_Horizontal_UV_Irradiance_295to385nm FLOAT NOT NULL
);

CREATE TABLE ingham_county_2018_lansing(
	Year INT NOT NULL, 
	Month INT NOT NULL,
	Day INT NOT NULL,
	Hour INT NOT NULL,
	Minute INT NOT NULL,
	DHI FLOAT NOT NULL,
	DNI FLOAT NOT NULL,
	GHI FLOAT NOT NULL,
	Clearsky_DHI FLOAT NOT NULL,
	Clearsky_DNI FLOAT NOT NULL,
	Clearsky_GHI FLOAT NOT NULL,
	Cloud_Type FLOAT NOT NULL,
	Dew_Point FLOAT NOT NULL,
	Solar_Zenith_Angle FLOAT NOT NULL,
	Fill_Flag FLOAT NOT NULL,
	Surface_Albedo FLOAT NOT NULL,
	Wind_Speed FLOAT NOT NULL,
	Precipitable_Water FLOAT NOT NULL,
	Wind_Direction FLOAT NOT NULL,
	Relative_Humidity FLOAT NOT NULL,
	Temperature FLOAT NOT NULL,
	Pressure FLOAT NOT NULL,
	Global_Horizontal_UV_Irradiance_280to400nm FLOAT NOT NULL,
	Global_Horizontal_UV_Irradiance_295to385nm FLOAT NOT NULL
);

CREATE TABLE kent_county_2018_grandrapids(
	Year INT NOT NULL, 
	Month INT NOT NULL,
	Day INT NOT NULL,
	Hour INT NOT NULL,
	Minute INT NOT NULL,
	DHI FLOAT NOT NULL,
	DNI FLOAT NOT NULL,
	GHI FLOAT NOT NULL,
	Clearsky_DHI FLOAT NOT NULL,
	Clearsky_DNI FLOAT NOT NULL,
	Clearsky_GHI FLOAT NOT NULL,
	Cloud_Type FLOAT NOT NULL,
	Dew_Point FLOAT NOT NULL,
	Solar_Zenith_Angle FLOAT NOT NULL,
	Fill_Flag FLOAT NOT NULL,
	Surface_Albedo FLOAT NOT NULL,
	Wind_Speed FLOAT NOT NULL,
	Precipitable_Water FLOAT NOT NULL,
	Wind_Direction FLOAT NOT NULL,
	Relative_Humidity FLOAT NOT NULL,
	Temperature FLOAT NOT NULL,
	Pressure FLOAT NOT NULL,
	Global_Horizontal_UV_Irradiance_280to400nm FLOAT NOT NULL,
	Global_Horizontal_UV_Irradiance_295to385nm FLOAT NOT NULL
);

CREATE TABLE mackinac_county_2018(
	Year INT NOT NULL, 
	Month INT NOT NULL,
	Day INT NOT NULL,
	Hour INT NOT NULL,
	Minute INT NOT NULL,
	DHI FLOAT NOT NULL,
	DNI FLOAT NOT NULL,
	GHI FLOAT NOT NULL,
	Clearsky_DHI FLOAT NOT NULL,
	Clearsky_DNI FLOAT NOT NULL,
	Clearsky_GHI FLOAT NOT NULL,
	Cloud_Type FLOAT NOT NULL,
	Dew_Point FLOAT NOT NULL,
	Solar_Zenith_Angle FLOAT NOT NULL,
	Fill_Flag FLOAT NOT NULL,
	Surface_Albedo FLOAT NOT NULL,
	Wind_Speed FLOAT NOT NULL,
	Precipitable_Water FLOAT NOT NULL,
	Wind_Direction FLOAT NOT NULL,
	Relative_Humidity FLOAT NOT NULL,
	Temperature FLOAT NOT NULL,
	Pressure FLOAT NOT NULL,
	Global_Horizontal_UV_Irradiance_280to400nm FLOAT NOT NULL,
	Global_Horizontal_UV_Irradiance_295to385nm FLOAT NOT NULL
);

CREATE TABLE oakland_county_2018(
	Year INT NOT NULL, 
	Month INT NOT NULL,
	Day INT NOT NULL,
	Hour INT NOT NULL,
	Minute INT NOT NULL,
	DHI FLOAT NOT NULL,
	DNI FLOAT NOT NULL,
	GHI FLOAT NOT NULL,
	Clearsky_DHI FLOAT NOT NULL,
	Clearsky_DNI FLOAT NOT NULL,
	Clearsky_GHI FLOAT NOT NULL,
	Cloud_Type FLOAT NOT NULL,
	Dew_Point FLOAT NOT NULL,
	Solar_Zenith_Angle FLOAT NOT NULL,
	Fill_Flag FLOAT NOT NULL,
	Surface_Albedo FLOAT NOT NULL,
	Wind_Speed FLOAT NOT NULL,
	Precipitable_Water FLOAT NOT NULL,
	Wind_Direction FLOAT NOT NULL,
	Relative_Humidity FLOAT NOT NULL,
	Temperature FLOAT NOT NULL,
	Pressure FLOAT NOT NULL,
	Global_Horizontal_UV_Irradiance_280to400nm FLOAT NOT NULL,
	Global_Horizontal_UV_Irradiance_295to385nm FLOAT NOT NULL
);

CREATE TABLE washtenaw_county_2018_annarbor(
	Year INT NOT NULL, 
	Month INT NOT NULL,
	Day INT NOT NULL,
	Hour INT NOT NULL,
	Minute INT NOT NULL,
	DHI FLOAT NOT NULL,
	DNI FLOAT NOT NULL,
	GHI FLOAT NOT NULL,
	Clearsky_DHI FLOAT NOT NULL,
	Clearsky_DNI FLOAT NOT NULL,
	Clearsky_GHI FLOAT NOT NULL,
	Cloud_Type FLOAT NOT NULL,
	Dew_Point FLOAT NOT NULL,
	Solar_Zenith_Angle FLOAT NOT NULL,
	Fill_Flag FLOAT NOT NULL,
	Surface_Albedo FLOAT NOT NULL,
	Wind_Speed FLOAT NOT NULL,
	Precipitable_Water FLOAT NOT NULL,
	Wind_Direction FLOAT NOT NULL,
	Relative_Humidity FLOAT NOT NULL,
	Temperature FLOAT NOT NULL,
	Pressure FLOAT NOT NULL,
	Global_Horizontal_UV_Irradiance_280to400nm FLOAT NOT NULL,
	Global_Horizontal_UV_Irradiance_295to385nm FLOAT NOT NULL
);

CREATE TABLE wayne_county_2018_detroit(
	Year INT NOT NULL, 
	Month INT NOT NULL,
	Day INT NOT NULL,
	Hour INT NOT NULL,
	Minute INT NOT NULL,
	DHI FLOAT NOT NULL,
	DNI FLOAT NOT NULL,
	GHI FLOAT NOT NULL,
	Clearsky_DHI FLOAT NOT NULL,
	Clearsky_DNI FLOAT NOT NULL,
	Clearsky_GHI FLOAT NOT NULL,
	Cloud_Type FLOAT NOT NULL,
	Dew_Point FLOAT NOT NULL,
	Solar_Zenith_Angle FLOAT NOT NULL,
	Fill_Flag FLOAT NOT NULL,
	Surface_Albedo FLOAT NOT NULL,
	Wind_Speed FLOAT NOT NULL,
	Precipitable_Water FLOAT NOT NULL,
	Wind_Direction FLOAT NOT NULL,
	Relative_Humidity FLOAT NOT NULL,
	Temperature FLOAT NOT NULL,
	Pressure FLOAT NOT NULL,
	Global_Horizontal_UV_Irradiance_280to400nm FLOAT NOT NULL,
	Global_Horizontal_UV_Irradiance_295to385nm FLOAT NOT NULL
);

CREATE TABLE deep_solar_house_installation_mich(
    tile_count INT NOT NULL,
    solar_system_count INT NOT NULL,
    total_panel_area FLOAT NOT NULL,
    fips VARCHAR(50),
    county VARCHAR(50),
    solar_panel_area_divided_by_area FLOAT,
    solar_panel_area_per_capita FLOAT,
    tile_count_residential INT,
    solar_system_count_residential INT,
    total_panel_area_residential FLOAT,
    lat FLOAT,
    lon FLOAT,
    daily_solar_radiation FLOAT,
    number_of_solar_system_per_household FLOAT
);
